# Generated by Django 4.0.4 on 2022-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_banner_cta_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='prueba_fields',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
