# Generated by Django 4.0.4 on 2022-06-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_prueba_fields_homepage_banner_cta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
    ]
