# Generated by Django 4.0.4 on 2022-06-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0014_oriente_alter_homepage_banner_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oriente',
            new_name='OrientePage',
        ),
    ]
