# Generated by Django 4.0.4 on 2022-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_orientepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientepage',
            name='descrip',
            field=models.CharField(default='text', max_length=250),
            preserve_default=False,
        ),
    ]
