# Generated by Django 4.0.4 on 2022-06-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_orientepage_descrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientepage',
            name='descrip',
        ),
    ]
