# Generated by Django 4.0.4 on 2022-06-03 21:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0018_remove_orientepage_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nombre_playa', wagtail.fields.RichTextField(default='nombre de la playa')),
                ('ubicacion_playa', wagtail.fields.RichTextField(default='direccion de la playa')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OccidentePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nombre_playa', wagtail.fields.RichTextField(default='nombre de la playa')),
                ('ubicacion_playa', wagtail.fields.RichTextField(default='direccion de la playa')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
