# Generated by Django 4.0.4 on 2022-06-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_blogpagegalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_image',
            new_name='blog_image',
        ),
    ]
